services:
  postgres:
    ports: !override ["127.0.0.1:55440:5432"]
  search:
    ports: !override ["127.0.0.1:19240:9200"]
  app:
    image: noticeboard-app:latest
    ports: !override ["127.0.0.1:8923:8000"]
